# Generated by Django 3.2.6 on 2024-10-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Facturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('monto', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturas.factura')),
            ],
        ),
    ]
