# Generated by Django 3.2.6 on 2024-10-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('dscripcion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('fechaIni', models.CharField(max_length=100)),
                ('fechaVen', models.CharField(max_length=100)),
                ('abonado', models.IntegerField()),
                ('intereses', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.estudiante')),
            ],
        ),
    ]
